name: Docker Image CI

on: push

jobs:
  docker-build:
    name: docker构建
    runs-on: ubuntu-latest
    steps:
    - name: 检出仓库代码
      uses: actions/checkout@v4
    - name: 设置 Docker 环境
      run: |
        echo "构建Docker镜像..."
        # 这里可以添加任何需要的设置步骤
    - name: 构建并标记 Docker 镜像
      run: docker build . --file Dockerfile --tag my-image-name:latest
